[build]
rustflags = [
    "-L", "C:\\rtools45\\x86_64-w64-mingw32.static.posix\\lib\\gcc\\x86_64-w64-mingw32.static.posix\\14.2.0",
    "-L", "D:\\gp\\local_tdx\\lib"
]

[target.x86_64-pc-windows-gnu]
linker = "rust-lld"

[source.crates-io]
replace-with = 'sjtu'

[source.sjtu]
registry = "sparse+https://mirrors.sjtug.sjtu.edu.cn/crates.io-index/"
